version: 2.1

jobs:
  build:
    context: kaggle-api
    working_directory: ~/ccibuild
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: kaggle competitions download -c titanic
      - run: unzip titanic.zip -d ./input
      - run: jupyter nbconvert --execute ./titanic.ipynb
      - run: kaggle competitions submit -f ./result.csv -m "Auto submission from Github repository"
      - store_artifacts:
          path: ./result.csv
